services:
  postgres:
    image: postgres:17
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: SNTB@13nkt
      POSTGRES_DB: sample
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - local-net

  redis:
    image: redis:7.4.2
    container_name: local-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "SNTB@13nkt"]
    volumes:
      - ./data/redis:/data
    networks:
      - local-net

  # OpenSearch với CORS enabled
  opensearch:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch
    restart: unless-stopped
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS}
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - plugins.security.ssl.http.enabled=false
      - logger.level=WARN
      # Thêm cấu hình CORS
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:3000,http://localhost:3001
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 2g
    volumes:
      - ${OPENSEARCH_DATA}:/usr/share/opensearch/data
      - ./logs:/usr/share/opensearch/logs
    networks:
      - local-net
    ports:
      - "9200:9200"

  # OpenSearch Dashboards
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.1
    container_name: ${OPENSEARCH_DASHBOARD_CONTAINER}
    ports:
      - "5601:5601"
    volumes:
      - ./config/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
      - ./logs:/usr/share/opensearch-dashboards/logs
    networks:
      - local-net
    depends_on:
      - opensearch
    restart: unless-stopped

networks:
  local-net:
    driver: bridge